### ISSUE TITLE
JS doesn't support i64 values

### ISSUE THREAD

**Issue by wanderer** [primea/js-primea-hypervisor#3]
Since JS currently doesn't support i64 values some function of the ethereum system interface will not correctly.

This can be fixed by transcompiling any import that has a i64 params to be two i32 params and transcompiling the where it get called 

The other option  would just to be to limit the system interface to only have i32 params

**Comment by wanderer** [comment]
https://github.com/WebAssembly/design/issues/515

**Comment by axic** [comment]
I would think (in agreement with the linked issue) it is a current problem with JS, to be eliminated in the next version.

It could stay i64 and instead of transcompiling, we would have a WASM wrapper code which does the (i32,i32) -> (i64) translation. This would only be present in the kernel (VM) written for and old JS version. and others, such as go-ethereum could use the fast, optimised path of i64.

**Comment by wanderer** [comment]
> we would have a WASM wrapper code which does the (i32,i32) -> (i64) translation

this is now done in the shim branch

**Comment by axic** [comment]
See #54
